// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeletePrediction(arg1) {
  return window['go']['main']['App']['DeletePrediction'](arg1);
}

export function ForceCheckResults() {
  return window['go']['main']['App']['ForceCheckResults']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDailyPrograms(arg1) {
  return window['go']['main']['App']['GetDailyPrograms'](arg1);
}

export function GetGanyanTypes(arg1, arg2) {
  return window['go']['main']['App']['GetGanyanTypes'](arg1, arg2);
}

export function GetPredictions() {
  return window['go']['main']['App']['GetPredictions']();
}

export function GetProgramSilks(arg1, arg2) {
  return window['go']['main']['App']['GetProgramSilks'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PerformUpdate() {
  return window['go']['main']['App']['PerformUpdate']();
}

export function SavePrediction(arg1) {
  return window['go']['main']['App']['SavePrediction'](arg1);
}

export function UpdatePrediction(arg1) {
  return window['go']['main']['App']['UpdatePrediction'](arg1);
}
