// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeletePrediction(arg1) {
  return window['go']['main']['App']['DeletePrediction'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDailyPrograms(arg1) {
  return window['go']['main']['App']['GetDailyPrograms'](arg1);
}

export function GetPredictions() {
  return window['go']['main']['App']['GetPredictions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PerformUpdate() {
  return window['go']['main']['App']['PerformUpdate']();
}

export function SavePrediction(arg1) {
  return window['go']['main']['App']['SavePrediction'](arg1);
}
