// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateResult>;

export function DeletePrediction(arg1:number):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetDailyPrograms(arg1:string):Promise<Array<main.RaceProgram>>;

export function GetGanyanTypes(arg1:string,arg2:string):Promise<Array<main.GanyanInfo>>;

export function GetPredictions():Promise<Array<main.Prediction>>;

export function GetProgramSilks(arg1:string,arg2:string):Promise<Record<number, Record<string, string>>>;

export function Greet(arg1:string):Promise<string>;

export function PerformUpdate():Promise<main.UpdateResult>;

export function SavePrediction(arg1:main.Prediction):Promise<void>;

export function UpdatePrediction(arg1:main.Prediction):Promise<void>;
